---
- name: "Logicwax new host init"
  become: true
  hosts: 127.0.0.1
  connection: local
  tasks:

    - name: Install APT packages
      apt:
        pkg:
        - ccze
        - emacs
        - fonts-powerline
        - gnupg2
        - gnutls-bin
        - gpgv
        - gpgv2
        - htop
        - keyutils
        - libccid
        - libpam-ssh-agent-auth
        - libpcsclite1
        - monkeysphere
        - ncdu
        - openssh-server
        - pass
        - pcscd
        - pgpdump
        - pinentry-tty
        - powerline
        - python-dev
        - rsync
        - scdaemon
        - strace
        - u2f-host
        - yubikey-personalization
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting

    - name: Install oh-my-zsh
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      args:
          creates: /home/{{ user }}/.oh-my-zsh
      become: yes
      become_user: "{{ user }}"

    - name: Changing shell to zsh
      shell: chsh -s /bin/zsh {{ user }}

    - name: Config oh-my-zsh theme
      block:
      - shell: "cp /home/{{ user }}/.oh-my-zsh/templates/zshrc.zsh-template /home/{{ user }}/.zshrc || true"
      - replace:
          path: /home/{{ user }}/.oh-my-zsh/themes/agnoster.zsh-theme
          regexp: '(?P<dirprompt>^\s+prompt_segment) blue \$CURRENT_FG'
          replace: '\g<dirprompt> 089 $CURRENT_FG'
      - lineinfile:
          dest: /home/{{ user }}/.zshrc
          state: present
          regexp: '^ZSH_THEME=.*'
          line: 'ZSH_THEME="agnoster"'
      - lineinfile:
          dest: /home/{{ user }}/.zshrc
          state: present
          insertafter: EOF
          line: 'source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh'
      - lineinfile:
          dest: /home/{{ user }}/.zshrc
          state: present
          insertafter: EOF
          line: 'source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh'
      become: yes
      become_user: "{{ user }}"

    - name: Assign root write-only ownership
      file:
        path: /etc/security/authorized_keys
        state: touch
        owner: root
        group: root
        mode: "0644"

    - name: Install SSH key
      authorized_key:
        user: "{{ user }}"
        state: present
        key: "{{ ssh_key_url }}"
        path: /etc/security/authorized_keys
        manage_dir: False

    - name: Configure SSHd to use authorized_keys
      lineinfile:
         dest: /etc/ssh/sshd_config
         state: present
         regexp: '.*#.*AuthorizedKeysFile.*'
         line: 'AuthorizedKeysFile  /etc/security/authorized_keys'

    - name: SUDO Yubikey Auth
      block:
      - lineinfile:
          dest: /etc/pam.d/common-auth
          state: present
          insertafter: BOF
          line: 'auth sufficient pam_ssh_agent_auth.so file=/etc/security/authorized_keys'
      - lineinfile:
          path: /etc/sudoers
          state: present
          insertafter: '^%sudo.*ALL=\(ALL:ALL\) ALL$'
          line: 'Defaults env_keep += SSH_AUTH_SOCK'
          validate: '/usr/sbin/visudo -cf %s'

    - name: Support GPG agent forwarding
      block:
      - lineinfile:
          dest: /etc/ssh/sshd_config
          state: present
          insertafter: EOF
          line: 'StreamLocalBindUnlink yes'
      - lineinfile:
          dest: /etc/ssh/sshd_config
          state: present
          regexp: '^PasswordAuthentication'
          line: 'PasswordAuthentication no'
      - lineinfile:
          dest: /home/{{ user }}/.gnupg/gpg-agent.conf
          state: present
          create: yes
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: "0644"
          insertafter: BOF
          line: 'enable-ssh-support'
      - lineinfile:
          dest: /home/{{ user }}/.gnupg/gpg-agent.conf
          state: present
          insertafter: 'enable-ssh-support'
          line: 'pinentry-program /usr/bin/pinentry-tty'


    - name: Yubikey SSH config for bash shell
      blockinfile:
        path: "/home/{{ user }}/.bashrc"
        block: |
          envfile="$HOME/.gnupg/gpg-agent.env"
          if ( [[ ! -e "$HOME/.gnupg/S.gpg-agent" ]] && \
          [[ ! -e "/var/run/user/$(id -u)/gnupg/S.gpg-agent" ]] );
          then
            killall pinentry > /dev/null 2>&1
            gpgconf --reload scdaemon > /dev/null 2>&1
            pkill -x -INT gpg-agent > /dev/null 2>&1
            gpg-agent --daemon --enable-ssh-support > $envfile
          fi
          export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
          export GPG_TTY=$(tty)
          gpg-connect-agent updatestartuptty /bye > /dev/null

    - name: Yubikey SSH config for z-shell
      blockinfile:
        path: "/home/{{ user }}/.zshrc"
        block: |
          envfile="$HOME/.gnupg/gpg-agent.env"
          if ( [[ ! -e "$HOME/.gnupg/S.gpg-agent" ]] && \
          [[ ! -e "/var/run/user/$(id -u)/gnupg/S.gpg-agent" ]] );
          then
            killall pinentry > /dev/null 2>&1
            gpgconf --reload scdaemon > /dev/null 2>&1
            pkill -x -INT gpg-agent > /dev/null 2>&1
            gpg-agent --daemon --enable-ssh-support > $envfile
          fi
          export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
          export GPG_TTY=$(tty)
          gpg-connect-agent updatestartuptty /bye > /dev/null
          alias yubireset="rm -rfv ~/.gnupg/private-keys-v1.d && killall -q gpg-agent ssh-agent scdaemon && source ~/.zshrc && gpg --card-status"

    - name: Some one-offs
      block:
      - lineinfile:
          path: /home/{{ user }}/.bashrc
          state: present
          insertafter: EOF
          line: 'alias emacs="emacs -nw "'
      - lineinfile:
          path: /home/{{ user }}/.zshrc
          state: present
          insertafter: EOF
          line: 'alias emacs="emacs -nw "'
      - lineinfile:
          dest: /home/{{ user }}/.byobu/.tmux.conf
          state: present
          create: yes
          owner: "{{ user }}"
          group: "{{ user }}"
          mode: "0644"
          insertafter: BOF
          line: 'set-option -g mouse on'

    - name: Create udev rule to auto-detect Yubikey insertion
      block:
        - template:
           src: templates/insert-yubi.sh
           dest: /usr/local/bin/
           mode: "0744"
        - template:
           src: templates/69.yubikey.rules
           dest: /etc/udev/rules.d/
           mode: "0644"
        - shell: "udevadm control -R"

    - name: Install emacs config
      shell: git clone  https://github.com/logicwax/emacsconfig.git /home/{{ user }}/.emacs.d
      args:
          creates: /home/{{ user }}/.emacs.d
      become: yes
      become_user: "{{ user }}"

    - name: Shrink massive GNOME titlebars to sane values
      template:
        src: templates/gtk.css
        dest: /home/{{ user }}/.config/gtk-3.0/gtk.css
        mode: "0644"
