---
- name: "SSH Key install"
  become: true
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install SSH key
      block:
      - file:
          path: /etc/security/authorized_keys
          state: touch
          owner: root
          group: root
          mode: "0644"
      - authorized_key:
          user: "{{ user }}"
          state: present
          key: "https://github.com/{{ github_account }}.keys"
          path: /etc/security/authorized_keys
          manage_dir: False
      - file:
          path: /etc/security/authorized_keys
          state: touch
          owner: root
          group: root
          mode: "0644"

    - name: Configure SSHd to use authorized_keys
      lineinfile:
        dest: /etc/ssh/sshd_config
        state: present
        regexp: '.*#.*AuthorizedKeysFile.*'
        line: 'AuthorizedKeysFile  /etc/security/authorized_keys'

    - name: Install GPG key
      shell: |
        KEY_ID=$(curl https://github.com/{{ github_account }}.gpg | gpg --with-colons --import-options import-show --import | awk -F: '/^pub:/ {print $5}')
        echo -e "5\n5\ny\n" | gpg --command-fd 0 --expert --edit-key "$KEY_ID" trust save quit
      become: yes
      become_user: "{{ user }}"